name: Terraform Workflow

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_yandex_token: ${{ secrets.YANDEX_TOKEN }}
      TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.3"

      - name: Terraform Init (Main)
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan (Main)
        working-directory: ./terraform
        id: plan_main
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true

      - name: Terraform Apply (Main)
        if: steps.plan_main.outcome == 'success' && steps.plan_main.conclusion == 'success' && !contains(steps.plan_main.outputs.stdout, 'No changes')
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan