apiVersion: v1
kind: Service
metadata:
  name: diplom-test-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: diplom-test-app
  ports:
    - name: http
      port: 80
      targetPort: 80